CREATE TABLE cbl_breweries (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  us_state TEXT NOT NULL,
  image TEXT,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);
