CREATE TABLE cbl_beers (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  style TEXT NOT NULL,
  abv TEXT,
  ibu TEXT,
  description TEXT,
  beer_color TEXT NOT NULL,
  rating INTEGER NOT NULL DEFAULT 1,
  CHECK (rating > 0 AND rating < 6),
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP,
  brewery_id INTEGER
    REFERENCES cbl_breweries(id) ON DELETE CASCADE NOT NULL
);
